name: CI
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches: [master]
jobs:
    build:
        name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['10.x', '12.x', '14.x']
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1

            - name: Build
              run: npm run build

            - name: Test
              run: npm test -- --ci --maxWorkers=2
    lint:
        name: Lint project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1

            - name: Lint
              run: npm run lint
